---
title: "DS 700 Final Project Part 1"
author: "Nick Lashinski"
output: html_notebook
---


```{r}
library(readr)
library(dplyr)
library(ggformula)
library(readxl)
library(lubridate)
library(Amelia)
library(zeligverse)
```
**Loading data**
```{r}
abbeville = read_excel("Dataset.xlsx", sheet =2)
violet = read_excel("Dataset.xlsx", sheet =3)
orleans = read_excel("Dataset.xlsx", sheet =4)
lafayette = read_excel("Dataset.xlsx", sheet =5)
baton = read_excel("Dataset.xlsx", sheet =6)
december = read_excel("Dataset.xlsx", sheet =7)
```
**Cleaning Abbeville Data**
```{r}
abbeville$`Incoming Examinations` <- as.numeric(abbeville$`Incoming Examinations`)
abbeville$`Incoming Examinations`[which(as.numeric(abbeville$`Incoming Examinations`) > 100000)] = NA
abbeville$Date <- as.Date(paste(abbeville$Year, abbeville$Month, "01", sep="-"))
summary(abbeville)
```

**Filtering and Cleaning Violet Data**
```{r}
heartKeywords = c("cardi|heart|angia|cor pulmonale|atrial|takotsubo|chordae|coronary")
violet$Examination <- tolower(violet$Examination)
#violet$Date <- transform(violet, date = ifelse(grepl(",", violet$Date), as.Date(violet$Date, "%d %b, %Y"), as.Date("1900-01-01") + as.integer(violet$Date)))
violetShortDate = dplyr::filter(violet, !grepl(",", Date))
violetLongDate = dplyr::filter(violet, grepl(",", Date))
violetShortDate$Date <- as.Date("1900-01-01") + as.integer(violetShortDate$Date)
violetLongDate$Date <- as.Date(violetLongDate$Date, "%d %b, %Y")
violetFixedDate <- rbind(violetShortDate, violetLongDate)
#summary(violet)
#summary(violetFixedDate)
violet_filtered = dplyr::filter(violetFixedDate, grepl(heartKeywords, Examination))
violet_filtered = dplyr::filter(violet_filtered, grepl("Abbeville", `Original Hospital Location`))
summary(violet_filtered)
violet_filtered$visit = 1
violet_visits = violet_filtered %>% group_by(month=floor_date(Date, "month")) %>%
   summarize(amount=sum(visit))
```
**Filtering and Cleaning Orleans Data**
```{r}
orleans$Examination <- tolower(orleans$Examination)
summary(orleans)
orleans$Date <- as.Date(orleans$Date)
orleans_filtered = dplyr::filter(orleans, grepl(heartKeywords, Examination))
orleans_filtered = dplyr::filter(orleans_filtered, grepl("Abbeville", `Original Hospital Location`))
summary(orleans_filtered)
orleans_filtered$visit = 1
orleans_visits = orleans_filtered %>% group_by(month=floor_date(Date, "month")) %>%
   summarize(amount=sum(visit))
```
**Filtering and Cleaning Lafayette Data**
```{r}
lafayette$Examination <- tolower(lafayette$Examination)
summary(lafayette)
lafayetteShortDate = dplyr::filter(lafayette, !grepl(",", Date))
lafayetteLongDate = dplyr::filter(lafayette, grepl(",", Date))
lafayetteShortDate$Date <- as.Date("1900-01-01") + as.integer(lafayetteShortDate$Date)
lafayetteLongDate$Date <- as.Date(lafayetteLongDate$Date, "%d %b, %Y")
lafayetteFixedDate <- rbind(lafayetteShortDate, lafayetteLongDate)
#summary(lafayetteFixedDate)
lafayette_filtered = dplyr::filter(lafayetteFixedDate, grepl(heartKeywords, Examination))
lafayette_filtered = dplyr::filter(lafayette_filtered, grepl("Abbeville", `Original Hospital Location`))
summary(lafayette_filtered)
lafayette_filtered$visit = 1
lafayette_visits = lafayette_filtered %>% group_by(month=floor_date(Date, "month")) %>%
   summarize(amount=sum(visit))
```
**Filtering and Cleaning Baton Data**
```{r}
baton$Examination <- tolower(baton$Examination)
summary(baton)
batonShortDate = dplyr::filter(baton, !grepl(",", Date))
batonLongDate = dplyr::filter(baton, grepl(",", Date))
batonShortDate$Date <- as.Date("1900-01-01") + as.integer(batonShortDate$Date)
batonLongDate$Date <- as.Date(batonLongDate$Date, "%d %b, %Y")
batonFixedDate <- rbind(batonShortDate, batonLongDate)
#summary(lafayetteFixedDate)
baton_filtered = dplyr::filter(batonFixedDate, grepl(heartKeywords, Examination))
baton_filtered = dplyr::filter(baton_filtered, grepl("Abbeville", `Original Hospital Location`))
summary(baton_filtered)
baton_filtered$visit = 1
baton_visits = baton_filtered %>% group_by(month=floor_date(Date, "month")) %>%
   summarize(amount=sum(visit))
```
**Filtering December 2013 Data**
```{r}
heartCodes = c("VVN284|PJU008|ABN441|UMP621|UMX710|TUX333|KPN015|RLX001|WPC608|LLA092|LLN112|TNR628|LOR159|KON421|KOZ198|ROB001")
december_filtered = dplyr::filter(december, startsWith(`Routing SYSID`, "L839"))
december_filtered2 = dplyr::filter(december_filtered, endsWith(`Routing SYSID`, "TGU3"))
december_filtered3 = dplyr::filter(december_filtered, endsWith(`Routing SYSID`, "ROV8"))
december_filtered4 = rbind(december_filtered2, december_filtered3)
december_filtered = dplyr::filter(december_filtered4, grepl(heartCodes, `Routing SYSID`))
summary(december_filtered)
```
**Collect totals for every month between all the data**
```{r}
#Missing data 200603 200606 200812 200905 200912 201001 201002 201006 201101 201112 201312

#values from the Explanation of Dataset PDF
Dec09 = 1709
Jan10 = 1710
Feb10 = 1710
abbeville$`Incoming Examinations`[which(abbeville$`Date` == '2009-12-01')] = Dec09
abbeville$`Incoming Examinations`[which(abbeville$`Date` == '2010-01-01')] = Jan10
abbeville$`Incoming Examinations`[which(abbeville$`Date` == '2010-02-01')] = Feb10
#setting the dec 2013 data
Dec13 = nrow(december_filtered)
abbeville$`Incoming Examinations`[which(abbeville$`Date` == '2013-12-01')] = Dec13
#getting visits from other locations
otherLocations <- rbind(violet_visits,orleans_visits,lafayette_visits,baton_visits)
otherLocationsTotals = otherLocations %>% group_by(Date=floor_date(month, "month")) %>%
   summarize(visits=sum(amount))
#adding vists from other locations
day1 = '2007-05-01'
abbeville$`Incoming Examinations`[which(abbeville$`Date` == day1)] = abbeville$`Incoming Examinations`[which(abbeville$`Date` == day1)] + otherLocationsTotals$`visits`[which(otherLocationsTotals$`Date` == day1)]
day2 = '2007-06-01'
abbeville$`Incoming Examinations`[which(abbeville$`Date` == day2)] = abbeville$`Incoming Examinations`[which(abbeville$`Date` == day2)] + otherLocationsTotals$`visits`[which(otherLocationsTotals$`Date` == day2)]
day3 = '2013-05-01'
abbeville$`Incoming Examinations`[which(abbeville$`Date` == day3)] = abbeville$`Incoming Examinations`[which(abbeville$`Date` == day3)] + otherLocationsTotals$`visits`[which(otherLocationsTotals$`Date` == day3)]
day4 = '2013-06-01'
abbeville$`Incoming Examinations`[which(abbeville$`Date` == day4)] = abbeville$`Incoming Examinations`[which(abbeville$`Date` == day4)] + otherLocationsTotals$`visits`[which(otherLocationsTotals$`Date` == day4)]
day5 = '2013-07-01'
abbeville$`Incoming Examinations`[which(abbeville$`Date` == day5)] = abbeville$`Incoming Examinations`[which(abbeville$`Date` == day5)] + otherLocationsTotals$`visits`[which(otherLocationsTotals$`Date` == day5)]
```
**Impute missing data**
```{r}
abbevilleSorted <- abbeville[order(abbeville$Date),]
colnames(abbevilleSorted) <- c("exams", "year", "month", "date")
imputedAbbeville = amelia(abbevilleSorted, m=5, ts='date', bounds=rbind(c(1, 0,10000)))

runs = bind_rows(imputedAbbeville$imputations[1],imputedAbbeville$imputations[2],imputedAbbeville$imputations[3],imputedAbbeville$imputations[4],imputedAbbeville$imputations[5])
completeData = runs %>% group_by(Date=floor_date(date, "month"), year, month) %>%
   summarize(visits=mean(exams))
```
**ARIMA Model**
```{r}
z1 <- zelig(formula = exams ~ month + year, model = "arima", order = c(1, 0, 0), data = imputedAbbeville)
summary(z1)
summary(z1, subset = 1:5)
#Getting future values
z1 <- setx(z1, month = 1, year = 2014)
z1 <- sim(z1)
jan2014 = mean(unlist(z1[["sim.out"]][["x"]][["ev"]]))
z1 <- setx(z1, month = 2, year = 2014)
z1 <- sim(z1)
feb2014 = mean(unlist(z1[["sim.out"]][["x"]][["ev"]]))
z1 <- setx(z1, month = 3, year = 2014)
z1 <- sim(z1)
mar2014 = mean(unlist(z1[["sim.out"]][["x"]][["ev"]]))
z1 <- setx(z1, month = 4, year = 2014)
z1 <- sim(z1)
apr2014 = mean(unlist(z1[["sim.out"]][["x"]][["ev"]]))
z1 <- setx(z1, month = 5, year = 2014)
z1 <- sim(z1)
may2014 = mean(unlist(z1[["sim.out"]][["x"]][["ev"]]))
z1 <- setx(z1, month = 6, year = 2014)
z1 <- sim(z1)
jun2014 = mean(unlist(z1[["sim.out"]][["x"]][["ev"]]))
z1 <- setx(z1, month = 7, year = 2014)
z1 <- sim(z1)
jul2014 = mean(unlist(z1[["sim.out"]][["x"]][["ev"]]))
z1 <- setx(z1, month = 8, year = 2014)
z1 <- sim(z1)
aug2014 = mean(unlist(z1[["sim.out"]][["x"]][["ev"]]))
z1 <- setx(z1, month = 9, year = 2014)
z1 <- sim(z1)
sep2014 = mean(unlist(z1[["sim.out"]][["x"]][["ev"]]))
z1 <- setx(z1, month = 10, year = 2014)
z1 <- sim(z1)
oct2014 = mean(unlist(z1[["sim.out"]][["x"]][["ev"]]))
z1 <- setx(z1, month = 11, year = 2014)
z1 <- sim(z1)
nov2014 = mean(unlist(z1[["sim.out"]][["x"]][["ev"]]))
z1 <- setx(z1, month = 12, year = 2014)
z1 <- sim(z1)
dec2014 = mean(unlist(z1[["sim.out"]][["x"]][["ev"]]))

#adding predicted values to data frame
predictionsARMIA = completeData
predictionsARMIA[nrow(predictionsARMIA) +1,] = list('2014-01-01',2014,1,as.integer(jan2014))
predictionsARMIA[nrow(predictionsARMIA) +1,] = list('2014-02-01',2014,2,as.integer(feb2014))
predictionsARMIA[nrow(predictionsARMIA) +1,] = list('2014-03-01',2014,3,as.integer(mar2014))
predictionsARMIA[nrow(predictionsARMIA) +1,] = list('2014-04-01',2014,4,as.integer(apr2014))
predictionsARMIA[nrow(predictionsARMIA) +1,] = list('2014-05-01',2014,5,as.integer(may2014))
predictionsARMIA[nrow(predictionsARMIA) +1,] = list('2014-06-01',2014,6,as.integer(jun2014))
predictionsARMIA[nrow(predictionsARMIA) +1,] = list('2014-07-01',2014,7,as.integer(jul2014))
predictionsARMIA[nrow(predictionsARMIA) +1,] = list('2014-08-01',2014,8,as.integer(aug2014))
predictionsARMIA[nrow(predictionsARMIA) +1,] = list('2014-09-01',2014,9,as.integer(sep2014))
predictionsARMIA[nrow(predictionsARMIA) +1,] = list('2014-10-01',2014,10,as.integer(oct2014))
predictionsARMIA[nrow(predictionsARMIA) +1,] = list('2014-11-01',2014,11,as.integer(nov2014))
predictionsARMIA[nrow(predictionsARMIA) +1,] = list('2014-12-01',2014,12,as.integer(dec2014))
write_csv(predictionsARMIA, "predictionsARMIA.csv")
```
**LS Model**
```{r}
z2 <- zelig(formula = exams ~ month + year, data = imputedAbbeville, model="ls")
summary(z2)
summary(z2, subset = 1:5)
#Getting future values
z2 <- setx(z2, month = 1, year = 2014)
z2 <- sim(z2)
jan2014 = mean(unlist(z2[["sim.out"]][["x"]][["ev"]]))
z2 <- setx(z2, month = 2, year = 2014)
z2 <- sim(z2)
feb2014 = mean(unlist(z2[["sim.out"]][["x"]][["ev"]]))
z2 <- setx(z2, month = 3, year = 2014)
z2 <- sim(z2)
mar2014 = mean(unlist(z2[["sim.out"]][["x"]][["ev"]]))
z2 <- setx(z2, month = 4, year = 2014)
z2 <- sim(z2)
apr2014 = mean(unlist(z2[["sim.out"]][["x"]][["ev"]]))
z2 <- setx(z2, month = 5, year = 2014)
z2 <- sim(z2)
may2014 = mean(unlist(z2[["sim.out"]][["x"]][["ev"]]))
z2 <- setx(z2, month = 6, year = 2014)
z2 <- sim(z2)
jun2014 = mean(unlist(z2[["sim.out"]][["x"]][["ev"]]))
z2 <- setx(z2, month = 7, year = 2014)
z2 <- sim(z2)
jul2014 = mean(unlist(z2[["sim.out"]][["x"]][["ev"]]))
z2 <- setx(z2, month = 8, year = 2014)
z2 <- sim(z2)
aug2014 = mean(unlist(z2[["sim.out"]][["x"]][["ev"]]))
z2 <- setx(z2, month = 9, year = 2014)
z2 <- sim(z2)
sep2014 = mean(unlist(z2[["sim.out"]][["x"]][["ev"]]))
z2 <- setx(z2, month = 10, year = 2014)
z2 <- sim(z2)
oct2014 = mean(unlist(z2[["sim.out"]][["x"]][["ev"]]))
z2 <- setx(z2, month = 11, year = 2014)
z2 <- sim(z2)
nov2014 = mean(unlist(z2[["sim.out"]][["x"]][["ev"]]))
z2 <- setx(z2, month = 12, year = 2014)
z2 <- sim(z2)
dec2014 = mean(unlist(z2[["sim.out"]][["x"]][["ev"]]))

#adding predicted values to data frame
predictionsLS = completeData
predictionsLS[nrow(predictionsLS) +1,] = list('2014-01-01',2014,1,as.integer(jan2014))
predictionsLS[nrow(predictionsLS) +1,] = list('2014-02-01',2014,2,as.integer(feb2014))
predictionsLS[nrow(predictionsLS) +1,] = list('2014-03-01',2014,3,as.integer(mar2014))
predictionsLS[nrow(predictionsLS) +1,] = list('2014-04-01',2014,4,as.integer(apr2014))
predictionsLS[nrow(predictionsLS) +1,] = list('2014-05-01',2014,5,as.integer(may2014))
predictionsLS[nrow(predictionsLS) +1,] = list('2014-06-01',2014,6,as.integer(jun2014))
predictionsLS[nrow(predictionsLS) +1,] = list('2014-07-01',2014,7,as.integer(jul2014))
predictionsLS[nrow(predictionsLS) +1,] = list('2014-08-01',2014,8,as.integer(aug2014))
predictionsLS[nrow(predictionsLS) +1,] = list('2014-09-01',2014,9,as.integer(sep2014))
predictionsLS[nrow(predictionsLS) +1,] = list('2014-10-01',2014,10,as.integer(oct2014))
predictionsLS[nrow(predictionsLS) +1,] = list('2014-11-01',2014,11,as.integer(nov2014))
predictionsLS[nrow(predictionsLS) +1,] = list('2014-12-01',2014,12,as.integer(dec2014))
write_csv(predictionsLS, "predictionsLS.csv")
```

